PUT http://localhost:8080/events/1
content-type: application/json

{
    "name": "Updated test event",
    "description": "A test event",
    "location": "Belfast",
    "dateTime": "2025-10-30T09:54:00.000Z"
}